# Jupyter Book Configuration
title: "Modelisation Numerique"
author: "Les auteurs du cours de Modelisation Numerique"
logo: ""
execute:
  execute_notebooks: "off"  # Turn off execution
  remove_cell_tags: ["solution"]  # Remove cells tagged with "solution"
html:
  theme: "sphinx_book_theme"
  favicon: ""  # Add the path to a favicon if needed
  launch_buttons:
    notebook_interface: "jupyterlab"
    colab_url: "https://colab.research.google.com/"
    binderhub_url: "https://mybinder.org"

